"""merge first+last into full_name

Revision ID: 8e8c61bf2b01
Revises: 8f7055f0ed79
Create Date: 2025-06-23 15:10:53.086271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8c61bf2b01'
down_revision: Union[str, None] = '8f7055f0ed79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('full_name', sa.String(length=50), nullable=False))
    op.drop_column('students', 'first_name')
    op.drop_column('students', 'last_name')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.add_column('students', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('students', 'full_name')
    # ### end Alembic commands ###
