"""Add region, city, school, academic_year models and update existing models2

Revision ID: aed5d35f4b67
Revises: 338e2ccd4712
Create Date: 2025-06-02 12:06:44.916020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed5d35f4b67'
down_revision: Union[str, None] = '338e2ccd4712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_subjects_teacher_id_fkey', 'teacher_subjects', type_='foreignkey')
    op.drop_constraint('teacher_subjects_subject_id_fkey', 'teacher_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_subjects', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_subjects', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('teachers_subject_id_fkey', 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'subject_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('teachers_subject_id_fkey', 'teachers', 'subjects', ['subject_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'teacher_subjects', type_='foreignkey')
    op.drop_constraint(None, 'teacher_subjects', type_='foreignkey')
    op.create_foreign_key('teacher_subjects_subject_id_fkey', 'teacher_subjects', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key('teacher_subjects_teacher_id_fkey', 'teacher_subjects', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
